name: Depreciation
description: See how much your asset will be worth year on year
pricing: Paid
available_as_addon: true
prices:
  - currency_code: NGN
    price: 10000
  - currency_code: USD
    price: 100
