name: Maintenance
description: We will help you keep your asset in tip tip shape
pricing: Paid
available_as_addon: true
prices:
  - currency_code: NGN
    price: 50000
  - currency_code: USD
    price: 500
