name: Basic
description: Popular plan for small
rank: 1
offers:
  - Up to 10 assets
  - Up to 1 seats
  - Asset register
  - Purchase insurance
  - Document manager
prices:
  - currency_code: NGN
    billing_cycle: Monthly
    amount: 0
  - currency_code: USD
    billing_cycle: Monthly
    amount: 0

  - currency_code: GBP
    billing_cycle: Monthly
    amount: 0
  - currency_code: EUR
    billing_cycle: Monthly
    amount: 0

  - currency_code: NGN
    billing_cycle: Yearly
    amount: 0

  - currency_code: USD
    billing_cycle: Yearly
    amount: 0

  - currency_code: GBP
    billing_cycle: Yearly
    amount: 0

  - currency_code: EUR
    billing_cycle: Yearly
    amount: 0
