name: Premium
description: Popular plan for medium teams
preceding_plan_name: Essential
rank: 3
offers:
  - Up to 250 assets
  - Up to 5 seats
  - Asset register
  - Up to 5 insurance policy
  - Purchase insurance
  - Document manager
  - Manage vendor
  - Up tp 5 workflow builder
  - API access
  - Asset checklist
  - Dedicated account manager
features:
  - name: Asset
    value: 250

  - name: Seat
    value: 5
prices:
  # Monthly
  - currency_code: NGN
    billing_cycle: Monthly
    amount: 80000
    processors:
      - name: Flutterwave
        id: 114486
  - currency_code: USD
    billing_cycle: Monthly
    amount: 2000
    processors:
      - name: Stripe
        id: price_1OXKZIB8pj3G5nb30EKj9qQd
  - currency_code: GBP
    billing_cycle: Monthly
    amount: 2000
    processors:
      - name: Stripe
        id: price_1OXKZlB8pj3G5nb3eC8MM2Mg
  - currency_code: EUR
    billing_cycle: Monthly
    amount: 2000
    processors:
      - name: Stripe
        id: price_1OXKZxB8pj3G5nb3dq1TLfx9

  # Yearly
  - currency_code: NGN
    billing_cycle: Yearly
    amount: 864000
    processors:
      - name: Flutterwave
        id: 114487
  - currency_code: USD
    billing_cycle: Yearly
    amount: 21600
    processors:
      - name: Stripe
        id: price_1OXKa8B8pj3G5nb3VvSgNFyo
  - currency_code: GBP
    billing_cycle: Yearly
    amount: 21600
    processors:
      - name: Stripe
        id: price_1OXKaOB8pj3G5nb3SEX70Ah5
  - currency_code: EUR
    billing_cycle: Yearly
    amount: 21600
    processors:
      - name: Stripe
        id: price_1OXKadB8pj3G5nb3Xa7ZwBAA
