name: Enterprise
description: Popular plan for large teams
preceding_plan_name: Premium Plus
rank: 5
offers:
  - Unlimited assets
  - Up to 20 seats
  - Asset register
  - Manage unlimited insurance policy
  - Purchase insurance
  - Asset audit
  - Document manager
  - Manage vendor
  - Depreciation
  - Unlimited workflow builder
  - API access
  - Asset checklist
  - Dedicated account manager
prices:
  - currency_code: NGN
    billing_cycle: MONTHLY
    amount: 250000
    processors:
      - name: flutterwave
        id: 61151
  - currency_code: USD
    billing_cycle: MONTHLY
    amount: 10000
    processors:
      - name: stripe
        id: 60139
  - currency_code: GBP
    billing_cycle: MONTHLY
    amount: 10000
    processors:
      - name: stripe
        id: 60139
  - currency_code: EUR
    billing_cycle: MONTHLY
    amount: 10000
    processors:
      - name: stripe
        id: 60139

  - currency_code: NGN
    billing_cycle: YEARLY
    amount: 2700000
    processors:
      - name: flutterwave
        id: 61152
  - currency_code: USD
    billing_cycle: YEARLY
    amount: 120000
    processors:
      - name: stripe
        id: 60139
  - currency_code: GBP
    billing_cycle: YEARLY
    amount: 120000
    processors:
      - name: stripe
        id: 60139
  - currency_code: EUR
    billing_cycle: YEARLY
    amount: 120000
    processors:
      - name: stripe
        id: 60139
