name: Enterprise
description: Popular plan for large teams
preceding_plan_name: Premium Plus
rank: 5
offers:
  - Unlimited assets
  - Up to 20 seats
  - Asset register
  - Unlimited insurance policy
  - Purchase insurance
  - Asset audit
  - Document manager
  - Manage vendor
  - Depreciation
  - Unlimited workflow builder
  - API access
  - Asset checklist
  - Dedicated account manager
features:
  - name: Asset
    value: Unlimited

  - name: Seat
    value: 20
prices:
  # Monthly
  - currency_code: NGN
    billing_cycle: Monthly
    amount: 250000
    slug: enterprise-ngn-monthly
    processors:
      - name: Flutterwave
        id: 114490

  - currency_code: USD
    billing_cycle: Monthly
    amount: 10000
    slug: enterprise-usd-monthly
    processors:
      - name: Stripe
        id: price_1OXKjEB8pj3G5nb3v3ebtaOO

  - currency_code: GBP
    billing_cycle: Monthly
    amount: 10000
    slug: enterprise-gbp-monthly
    processors:
      - name: Stripe
        id: price_1OXKjcB8pj3G5nb35QAwXM7U

  - currency_code: EUR
    billing_cycle: Monthly
    amount: 10000
    slug: enterprise-eur-monthly
    processors:
      - name: Stripe
        id: price_1OXKjtB8pj3G5nb37DIGHsBE

  # Yearly
  - currency_code: NGN
    billing_cycle: Yearly
    amount: 2700000
    slug: enterprise-ngn-yearly
    processors:
      - name: Flutterwave
        id: 114491

  - currency_code: USD
    billing_cycle: Yearly
    amount: 120000
    slug: enterprise-usd-yearly
    processors:
      - name: Stripe
        id: price_1OXKkEB8pj3G5nb3zdnvvQSh

  - currency_code: GBP
    billing_cycle: Yearly
    amount: 120000
    slug: enterprise-gbp-yearly
    processors:
      - name: Stripe
        id: price_1OXKklB8pj3G5nb3MFZkpB1Y

  - currency_code: EUR
    billing_cycle: Yearly
    amount: 120000
    slug: enterprise-eur-yearly
    processors:
      - name: Stripe
        id: price_1OXKl6B8pj3G5nb304XTZd1Y
