name: Enterprise
description: Popular plan for large teams
preceding_plan_name: Premium Plus
rank: 5
offers:
  - Unlimited assets
  - Up to 20 seats
  - Asset register
  - Unlimited insurance policy
  - Purchase insurance
  - Asset audit
  - Document manager
  - Manage vendor
  - Depreciation
  - Unlimited workflow builder
  - API access
  - Asset checklist
  - Dedicated account manager
features:
  - name: Asset
    value: Unlimited

  - name: Seat
    value: 20
prices:
  - currency_code: NGN
    billing_cycle: Monthly
    amount: 250000
    processors:
      - name: Flutterwave
        id: 61151
  - currency_code: USD
    billing_cycle: Monthly
    amount: 10000
    processors:
      - name: Stripe
        id: 60139
  - currency_code: GBP
    billing_cycle: Monthly
    amount: 10000
    processors:
      - name: Stripe
        id: 60139
  - currency_code: EUR
    billing_cycle: Monthly
    amount: 10000
    processors:
      - name: Stripe
        id: 60139

  - currency_code: NGN
    billing_cycle: Yearly
    amount: 2700000
    processors:
      - name: Flutterwave
        id: 61152
  - currency_code: USD
    billing_cycle: Yearly
    amount: 120000
    processors:
      - name: Stripe
        id: 60139
  - currency_code: GBP
    billing_cycle: Yearly
    amount: 120000
    processors:
      - name: Stripe
        id: 60139
  - currency_code: EUR
    billing_cycle: Yearly
    amount: 120000
    processors:
      - name: Stripe
        id: 60139
