name: Basic
description: Advanced managing of personnel and vendors
preceding_plan_name: Free
offers:
  - Up to 50 assets
  - Up to 3 seats
  - Asset Register
  - Document Manager
  - Manage Personnel
  - Manage vendor
  - Manage Insurance
prices:
  - currency_code: NGN
    billing_cycle: MONTHLY
    amount: 20000
    processors:
      - name: flutterwave
        id: 59365
  - currency_code: USD
    billing_cycle: MONTHLY
    amount: 50
  - currency_code: NGN
    billing_cycle: YEARLY
    amount: 240000
    processors:
      - name: flutterwave
        id: 59367
  - currency_code: USD
    billing_cycle: YEARLY
    amount: 600
