name: Classic
description: Popular plan for medium teams
preceding_plan_name: Basic
offers:
  - Up to 250 assets
  - Up to 5 seats
  - Asset Register
  - Document Manager
  - Manage Personnel
  - Manage vendor
  - Manage Insurance
  - Depreciation
prices:
  - currency_code: NGN
    billing_cycle: MONTHLY
    amount: 120000
    processors:
      - name: flutterwave
        id: 60064
  - currency_code: USD
    billing_cycle: MONTHLY
    amount: 300
    processors:
      - name: flutterwave
        id: 60137
    # - name: stripe
    #   id: 59367
  - currency_code: NGN
    billing_cycle: YEARLY
    amount: 1440000
    processors:
      - name: flutterwave
        id: 60065
  - currency_code: USD
    billing_cycle: YEARLY
    amount: 3600
    processors:
      - name: flutterwave
        id: 60138
    #   - name: stripe
    #     id: 59367