name: Free
description: Popular plan for small teams
offers:
  - Up to 10 assets
  - Only 1 user
  - Asset Register
  - Manage Insurance
prices:
  - currency_code: NGN
    billing_cycle: MONTHLY
    amount: 0
  - currency_code: USD
    billing_cycle: MONTHLY
    amount: 0
  - currency_code: NGN
    billing_cycle: YEARLY
    amount: 0
  - currency_code: USD
    billing_cycle: YEARLY
    amount: 0
