name: Premium
description: Popular plan for large teams
preceding_plan_name: Classic
offers:
  - Up to 1000 assets
  - Up to 10 seats
  - Asset Register
  - Document Manager
  - Manage Personnel
  - Manage vendor
  - Manage Insurance
  - Depreciation
  - Audit
  - Workflow Builder
  - API Access
prices:
  - currency_code: NGN
    billing_cycle: MONTHLY
    amount: 400000
  - currency_code: USD
    billing_cycle: MONTHLY
    amount: 1000
  - currency_code: NGN
    billing_cycle: YEARLY
    amount: 4800000
  - currency_code: USD
    billing_cycle: YEARLY
    amount: 12000
